<a href="https://colab.research.google.com/github/NaufalMajid11699/DataMining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunanakan untuk komputasi matris. Matplotlib merupakan library pythonuntuk presentasi data berubah grafik atau plot......

In [31]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [32]:
print(x)

[['klaten' 44.0 72000.0]
 ['ungaran' 27.0 48000.0]
 ['semarang' 30.0 54000.0]
 ['klaten' 38.0 61000.0]
 ['ungaran' 40.0 nan]
 ['semarang' 35.0 58000.0]
 ['klaten' nan 52000.0]
 ['ungaran' 48.0 79000.0]
 ['semarang' 50.0 83000.0]
 ['ungaran' 37.0 67000.0]]


In [33]:
print(y)

['no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes']


In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [36]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 40.0 nan]
 [1.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 nan 52000.0]
 [1.0 0.0 0.0 1.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 1.0 37.0 67000.0]]


In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [38]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state =1)

In [40]:
print(x_train)

[[0.0 1.0 0.0 0.0 nan 52000.0]
 [1.0 0.0 0.0 1.0 40.0 nan]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 1.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 35.0 58000.0]]


In [41]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 37.0 67000.0]]


In [42]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [43]:
print(y_test)

[0 1]


In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train [:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [45]:
print(x_train)

[[0.0 1.0 0.0 -0.7745966692414834 nan -1.0182239953527132]
 [1.0 0.0 0.0 1.2909944487358056 -0.038910211282047996 nan]
 [0.0 1.0 0.0 -0.7745966692414834 0.5058327466666259 0.583476671494251]
 [0.0 1.0 0.0 -0.7745966692414834 -0.3112816902563849 -0.2974586952715793]
 [1.0 0.0 0.0 1.2909944487358056 -1.809324824615238 -1.3385641287221062]
 [1.0 0.0 0.0 1.2909944487358056 1.0505757046152997 1.1440719048906884]
 [1.0 0.0 1.0 -0.7745966692414834 1.3229471835896367 1.4644120382600814]
 [1.0 0.0 1.0 -0.7745966692414834 -0.7198389087178904 -0.537713795298624]]
